Remove chardet<5 requirement
thombashi/mbstrdecoder pull request #6
Opened 2022-08-04 12:29 UTC by karolinku

Version 5.0.0 of chardet was released, it would be good
to support it.

2022-08-04 12:51 UTC, karolinku commented
This PR is related to work on packaging mbstrdecoder into fedora https://bugzilla.redhat.com/show_bug.cgi?id=2089243

2022-08-06 07:02 UTC, thombashi requested changes

2022-08-08 09:04 UTC, karolinku commented on requirements/requirements.txt
> +chardet>=3.0.4
done

2022-08-11 09:12 UTC, thombashi approved these changes
LGTM
Thank you for your contribution.

2022-08-11 09:12 UTC, merged